import { Component, signal } from '@angular/core';
import { MapaRutasComponent } from './components/mapa-rutas/mapa-rutas';
import { RutaData } from './models/ruta';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [MapaRutasComponent],
  template: `<app-mapa-rutas [rutaData]="rutaData()" />`,
})
export class AppComponent {
  rutaData = signal<RutaData>({
    id_ruta: 'ruta-demo-001',
    fecha_creacion: '2026-03-12T09:00:00.000000+00:00',
    almacen: {
      latitud: 19.0451781,
      longitud: -98.2458569,
      tiempo_recarga: 2700,
    },
    puntos_entrega: [
      {
        id: 1,
        nombre: 'Tienda Reforma',
        latitud: 19.058,
        longitud: -98.21,
        garrafones: 6,
        prioridad: 0,
        ventana_tiempo_inicia: 28800,
        ventana_tiempo_fin: 64800,
        estado: 'pendiente',
      },
      {
        id: 2,
        nombre: 'Abarrotes Angelópolis',
        latitud: 18.998,
        longitud: -98.245,
        garrafones: 4,
        prioridad: 0,
        ventana_tiempo_inicia: 28800,
        ventana_tiempo_fin: 64800,
        estado: 'pendiente',
      },
      {
        id: 3,
        nombre: 'Mercado Xonaca',
        latitud: 19.048,
        longitud: -98.18,
        garrafones: 8,
        prioridad: 0,
        ventana_tiempo_inicia: 28800,
        ventana_tiempo_fin: 64800,
        estado: 'pendiente',
      },
      {
        id: 4,
        nombre: 'Col. La Paz',
        latitud: 19.015,
        longitud: -98.195,
        garrafones: 3,
        prioridad: 0,
        ventana_tiempo_inicia: 28800,
        ventana_tiempo_fin: 64800,
        estado: 'pendiente',
      },
      {
        id: 5,
        nombre: 'San Baltazar',
        latitud: 19.075,
        longitud: -98.165,
        garrafones: 5,
        prioridad: 0,
        ventana_tiempo_inicia: 28800,
        ventana_tiempo_fin: 64800,
        estado: 'pendiente',
      },
      {
        id: 6,
        nombre: 'Cholula Centro',
        latitud: 19.063,
        longitud: -98.305,
        garrafones: 7,
        prioridad: 0,
        ventana_tiempo_inicia: 28800,
        ventana_tiempo_fin: 64800,
        estado: 'pendiente',
      },
      {
        id: 7,
        nombre: 'Lomas de Angelópolis',
        latitud: 19.005,
        longitud: -98.28,
        garrafones: 4,
        prioridad: 0,
        ventana_tiempo_inicia: 28800,
        ventana_tiempo_fin: 64800,
        estado: 'pendiente',
      },
      {
        id: 8,
        nombre: 'Col. Universidades',
        latitud: 19.07,
        longitud: -98.235,
        garrafones: 6,
        prioridad: 0,
        ventana_tiempo_inicia: 28800,
        ventana_tiempo_fin: 64800,
        estado: 'pendiente',
      },
      {
        id: 9,
        nombre: 'Zona Esmeralda',
        latitud: 19.028,
        longitud: -98.265,
        garrafones: 3,
        prioridad: 0,
        ventana_tiempo_inicia: 28800,
        ventana_tiempo_fin: 64800,
        estado: 'pendiente',
      },
    ],
    capacidad_camion: 72,
    num_camiones: 1,
    hash_peticion: 'demo-hash-001',
    pasos_ruta: [
      {
        cliente_id: 0,
        tipo: 'almacen',
        lat: 19.0451781,
        lon: -98.2458569,
        distancia: 0,
        duracion: 0,
        servicio: 0,
        carga_camion: 46,
      },
      {
        cliente_id: 8,
        tipo: 'entrega',
        lat: 19.07,
        lon: -98.235,
        distancia: 3200,
        duracion: 310,
        servicio: 360,
        carga_camion: 40,
      },
      {
        cliente_id: 1,
        tipo: 'entrega',
        lat: 19.058,
        lon: -98.21,
        distancia: 7100,
        duracion: 620,
        servicio: 360,
        carga_camion: 34,
      },
      {
        cliente_id: 5,
        tipo: 'entrega',
        lat: 19.075,
        lon: -98.165,
        distancia: 13400,
        duracion: 980,
        servicio: 300,
        carga_camion: 29,
      },
      {
        cliente_id: 3,
        tipo: 'entrega',
        lat: 19.048,
        lon: -98.18,
        distancia: 17800,
        duracion: 1250,
        servicio: 480,
        carga_camion: 21,
      },
      {
        cliente_id: 4,
        tipo: 'entrega',
        lat: 19.015,
        lon: -98.195,
        distancia: 23100,
        duracion: 1680,
        servicio: 180,
        carga_camion: 18,
      },
      {
        cliente_id: 9,
        tipo: 'entrega',
        lat: 19.028,
        lon: -98.265,
        distancia: 29500,
        duracion: 2100,
        servicio: 180,
        carga_camion: 15,
      },
      {
        cliente_id: 7,
        tipo: 'entrega',
        lat: 19.005,
        lon: -98.28,
        distancia: 35200,
        duracion: 2540,
        servicio: 240,
        carga_camion: 11,
      },
      {
        cliente_id: 2,
        tipo: 'entrega',
        lat: 18.998,
        lon: -98.245,
        distancia: 39800,
        duracion: 2890,
        servicio: 240,
        carga_camion: 7,
      },
      {
        cliente_id: 6,
        tipo: 'entrega',
        lat: 19.063,
        lon: -98.305,
        distancia: 51200,
        duracion: 3580,
        servicio: 420,
        carga_camion: 0,
      },
      {
        cliente_id: 0,
        tipo: 'almacen',
        lat: 19.0451781,
        lon: -98.2458569,
        distancia: 58900,
        duracion: 4150,
        servicio: 0,
        carga_camion: 0,
      },
    ],
    distancia_total: 58900,
    numero_viajes: 1,
    total_garrafones: 46,
  });
}
